# -*- coding: utf-8 -*-
"""graph_clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iEe6jNQeWRs5Z9tylScDx_e_dO4xH0CZ
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import cv2
import matplotlib.pyplot as plt
# %matplotlib inline
import networkx as nx
from skimage.io import imread
from skimage.morphology import skeletonize
from visibility_graph import visibility_graph
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC
from sklearn import metrics
from ts2vg import NaturalVG
from ts2vg import HorizontalVG

def clustering_coeff_feat(image):
    clus_coef_nat = []
    clus_coef_hor = []
    for i in range(64):
        series = image[i,:]
        nvg = NaturalVG()
        nvg.build(series)
        g = nvg.as_networkx()
        clus_coefs = list(nx.clustering(g).values())
        clus_coef_nat.append(clus_coefs)
        hvg = HorizontalVG()
        hvg.build(series)
        g1 = hvg.as_networkx()
        clus_coefs = list(nx.clustering(g1).values())
        clus_coef_hor.append(clus_coefs)

    #storing all rows in 64x64 array
    cluscoeff_nx_nat = np.array(clus_coef_nat)
    cluscoeff_nx_hor = np.array(clus_coef_hor)

    cluscoef_1_nat = []
    cluscoef_1_hor = []
    for i in range(64):
        series = image[:,i]
        nvg = NaturalVG()
        nvg.build(series)
        g = nvg.as_networkx()
        clus_coefs = list(nx.clustering(g).values())
        cluscoef_1_nat.append(clus_coefs)
        hvg = HorizontalVG()
        hvg.build(series)
        g1 = hvg.as_networkx()
        clus_coefs = list(nx.clustering(g1).values())
        cluscoef_1_hor.append(clus_coefs)

    #storing all column in 64x64 array
    cluscoef_1_nx_nat = np.array(cluscoef_1_nat)
    cluscoef_1_nx_hor = np.array(cluscoef_1_hor)

    # Storing both row clustering coeff and column clustering in cluscoef_201 64x64 array
    cluscoef_201_nat = cluscoeff_nx_nat + cluscoef_1_nx_nat
    cluscoef_201_hor = cluscoeff_nx_hor + cluscoef_1_nx_hor

    vgd_nat = np.zeros((64,64))
    vgd_hor = np.zeros((64,64))
    for i in range(-62,0,1):
        series = image[::-1,:].diagonal(i)
        vg = NaturalVG()
        vg.build(series)
        g = vg.as_networkx()
        clus_coefs = list(nx.clustering(g).values())
        index1 = i+63
        row_index , col_index = np.array(np.arange(index1,-1,-1)), np.array(np.arange(0,index1+1,1))
        vgd_nat[row_index,col_index] = clus_coefs
        hvg = HorizontalVG()
        hvg.build(series)
        g1 = hvg.as_networkx()
        clus_coefs = list(nx.clustering(g1).values())
        row_index , col_index = np.array(np.arange(index1,-1,-1)), np.array(np.arange(0,index1+1,1))
        vgd_hor[row_index,col_index] = clus_coefs

    for i in range(0,63,1):
        series = image[::-1,:].diagonal(i)
        vg = NaturalVG()
        vg.build(series)
        g = vg.as_networkx()
        clus_coefs = list(nx.clustering(g).values())
        index1 = i
        row_index , col_index = np.array(np.arange(index1,64,1)), np.array(np.arange(63,index1-1,-1))
        vgd_nat[row_index,col_index] = clus_coefs
        hvg = HorizontalVG()
        hvg.build(series)
        g1 = hvg.as_networkx()
        clus_coefs = list(nx.clustering(g1).values())
        index1 = i
        row_index , col_index = np.array(np.arange(index1,64,1)), np.array(np.arange(63,index1-1,-1))
        vgd_hor[row_index,col_index] = clus_coefs

    vgd_1_nat = np.zeros((64,64))
    vgd_1_hor = np.zeros((64,64))
    for i in range(62,0,-1):
        series = image.diagonal(i)
        vg = NaturalVG()
        vg.build(series)
        g = vg.as_networkx()
        clus_coefs = list(nx.clustering(g).values())
        index1 = -i + 64
        row_index , col_index = np.array(np.arange(0,index1,1)), np.array(np.arange(i,64,1))
        vgd_1_nat[row_index,col_index] = clus_coefs
        hvg = HorizontalVG()
        hvg.build(series)
        g1 = hvg.as_networkx()
        clus_coefs = list(nx.clustering(g1).values())
        index1 = -i + 64
        row_index , col_index = np.array(np.arange(0,index1,1)), np.array(np.arange(i,64,1))
        vgd_1_hor[row_index,col_index] = clus_coefs

    for i in range(0,-63,-1):
        series = image.diagonal(i)
        vg = NaturalVG()
        vg.build(series)
        g = vg.as_networkx()
        g = visibility_graph(series)
        clus_coefs = list(nx.clustering(g).values())
        index1 = i + 64
        row_index , col_index = np.array(np.arange(-i,64,1)), np.array(np.arange(0,index1,1))
        vgd_1_nat[row_index,col_index] = clus_coefs
        hvg = HorizontalVG()
        hvg.build(series)
        g1 = hvg.as_networkx()
        clus_coefs = list(nx.clustering(g1).values())
        index1 = i + 64
        row_index , col_index = np.array(np.arange(-i,64,1)), np.array(np.arange(0,index1,1))
        vgd_1_hor[row_index,col_index] = clus_coefs

    feature_mat_nat = cluscoef_201_nat + vgd_nat + vgd_1_nat
    feature_mat_hor = cluscoef_201_hor + vgd_hor + vgd_1_hor
    feature_mat_nat_hor = feature_mat_nat + feature_mat_hor
    feature_mat_nat = feature_mat_nat.flatten()
    feature_mat_hor = feature_mat_hor.flatten()
    feature_mat_nat_hor = feature_mat_nat_hor.flatten()
    return feature_mat_nat, feature_mat_hor, feature_mat_nat_hor

